# Generated by Django 5.1.1 on 2025-03-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="latestTrade",
            field=models.TextField(
                blank=True, default="e1c4b7ea-a3a6-4a2e-87f5-d549f9576dd3", null=True
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="latestTradeAmount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
